name: "Setup"
description: "Performs basic setup for steps utilizing Gradle"
runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: jetbrains
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash