image: saschpe/android-sdk:35-jdk21.0.6_7

pipelines:
  custom:
    main:
      - parallel:
          - step:
              name: Android lint
              caches:
                - gradle
              script:
                - ./gradlew lint --continue
              artifacts:
                - app/build/reports/**
          - step:
              name: Unit tests
              caches:
                - gradle
              artifacts:
                - 'build/reports/jacoco/jacocoTestReport/html/**'
              script:
                - ./gradlew jacocoTestReport --continue
          - step:
              name: Ktlint check
              caches:
                - gradle
              artifacts:
                - '*/build/reports/ktlint/ktlintMainSourceSetCheck/**'
              script:
                - ./gradlew ktlintMainSourceSetCheck --continue
      - step:
          name: Build APK
          caches:
            - gradle
          script:
            - ./gradlew app:assembleDebug