image: saschpe/android-sdk:35-jdk21.0.6_7

pipelines:
  custom:
    main:
      - parallel:
          - step:
              name: Unit tests
              caches:
                - gradle
              artifacts:
                - '*/build/reports/tests/**'
              script:
                - ./gradlew jvmTest --continue
          - step:
              name: Ktlint check
              caches:
                - gradle
              artifacts:
                - '*/build/reports/ktlint/**'
              script:
                - ./gradlew ktlintCommonMainSourceSetCheck --continue
                - ./gradlew ktlintAndroidMainSourceSetCheck --continue
                - ./gradlew ktlintJvmMainSourceSetCheck --continue
          - step:
              name: Android lint
              caches:
                - gradle
              script:
                - ./gradlew lint --continue
              artifacts:
                - '*/build/reports/lint-results-debug.*'
      - parallel:
          - step:
              name: Build Android
              caches:
                - gradle
              script:
                - ./gradlew app-android:assembleDebug
          - step:
              name: Build desktop
              caches:
                - gradle
              script:
                - ./gradlew app-desktop:createDistributable